#! /bin/sh

DESTDIR=${1:-/srv/http/woozle.org/xmas}

for img in */*.jpg; do
	target=$DESTDIR/${img%.jpg}-sm.jpg
	if older $target $img; then
		echo "SCALE $img"
		jpegtopnm $img | pnmscale -xysize 400 400 | pnmtojpeg > $target
	fi
done
